# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 
from snakemake.utils import validate


configfile: "config/config.yaml"


#container: "docker://condaforge/mambaforge:4.10.3-6"


include: "rules/common.smk"
include: "rules/resources.smk"
include: "rules/qc_reads.smk"
include: "rules/counts.smk"
include: "rules/seurat.smk"
include: "rules/singler.smk"
include: "rules/vdj.smk"
if config["pipeline"]=="cellranger":
    rule report:
        input:
            "results/multiqc/multiqc.html",
            expand("results/seurat/{sample}/{sample}_seurat.rds", sample=SAMPLES),
            "results/integration/integrated.rds",
            "results/singler/singler_results.csv",
            "results/enrichment/singler/"

if config["pipeline"]=="spaceranger":
    rule report:
        input:
            "results/multiqc/multiqc.html",
            expand("results/seurat/{sample}/{sample}_seurat.rds", sample=SAMPLES)

if config["pipeline"]=="multi":
    rule report:
        input:
            "results/multiqc/multiqc.html",
            expand("results/seurat/{sample}/{sample}_seurat.rds", sample=SAMPLES),
            "results/integration/integrated.rds",
            "results/singler/singler_results.csv",
            "results/ct",
            #"results/enrichment/singler/",