# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 
from snakemake.utils import validate


configfile: "config/config.yaml"


#container: "docker://condaforge/mambaforge:4.10.3-6"


include: "rules/common.smk"
include: "rules/resources.smk"
include: "rules/qc_reads.smk"
include: "rules/counts.smk"
include: "rules/seurat.smk"


rule report:
    input:
        "results/multiqc/multiqc.html",
        expand("results/counts/{sample}_cr/outs/web_summary.html", sample=SAMPLES),
        expand("results/seurat/{sample}/{sample}_seurat.rds", sample=SAMPLES),
        "results/integration/integrated.rds",
