rule cpdb:
    input: 
        rds="results/integration/integrated.rds",
    output:
        "results/cpdb/res.rds",
        temp("results/cpdb/matrix.mtx"),
        temp("results/cpdb/features.tsv"),
        temp("results/cpdb/barcodes.tsv"),
        temp("results/cpdb/meta.tsv"),
    log:
        "results/logs/cpdb.log",
    benchmark:
        "results/benchmarks/cpdb.txt",
    priority:
        1,
    conda:
        "seurat4",
    threads:
        10,
    script:
        "../scripts/cpdb.R"