rule cpdb:
    input: 
        rds="results/integration/integrated.rds",
    output:
        "results/cpdb/res.rds",
        "results/cpdb/matrix.mtx",
        "results/cpdb/features.tsv",
        "results/cpdb/barcodes.tsv",
        "results/cpdb/meta.tsv",
    log:
        "results/logs/cpdb.log",
    benchmark:
        "results/benchmarks/cpdb.txt",
    priority:
        1,
    conda:
        "/public/home/weiyifan/miniforge3/envs/cpdb",
    script:
        "../scripts/cpdb.R"