samples: "config/config_templete/samples_multi.yaml"
species: "homo_sapiens"
pipeline: "multi"
fq_type:
  - "R1"
  - "R2"
  - "I1"
  - "I2"
#仅在multi流程使用, TCR|BCR
vdj_type: "BCR"

get_cellranger:
  cellranger: 
    bin: "/public/home/weiyifan/xzm/soft/cellranger-7.2.0/cellranger"
  spaceranger: 
    bin: "/public/home/weiyifan/xzm/soft/spaceranger-3.1.1/spaceranger"
  multi:
    bin: "/public/home/weiyifan/xzm/soft/cellranger-7.2.0/cellranger"


get_reference:
  homo_sapiens: "/public/ref/reference/cellranger/refdata-gex-GRCh38-2020-A/"
  mus_musculus: "/public/home/weiyifan/xzm/ref/10x/refdata-gex-mm10-2020-A/"

counts:
  introns: False
  n_cells: 3000
  mem: 190

filter_empty:
  niters: 30000

qc:
  pct_counts_mt: 5
  total_counts: 60000
  n_genes_by_counts: 2000

dim_reduc:
  var_thresh: 0.75

cluster:
  res: 0.5
  markers:
    - "YOUR"
    - "FAVOURITE"
    - "GENE"

vdj_type: "TCR"