samples: "config/config_templete/samples_space.yaml"
# mus_musculus|homo_sapiens
species: "mus_musculus" 
 # cellranger|spaceranger|multi
pipeline: "spaceranger"
# index类型,根据原始数据后缀修改
fq_type:
  - "R1"
  - "R2"

counts:
  introns: False
  n_cells: 3000
  mem: 100

#仅在multi流程使用, TCR|BCR
vdj_type:

#此行以下不用修改
get_cellranger:
  cellranger: 
    bin: "/public/home/xiezhuoming/xzm/soft/cellranger-7.2.0/cellranger"
  spaceranger: 
    bin: "/public/home/xiezhuoming/xzm/soft/spaceranger-3.1.1/spaceranger"
  multi:
    bin: "/public/home/xiezhuoming/xzm/soft/cellranger-7.2.0/cellranger"


get_reference:
  homo_sapiens: "/public/ref/reference/cellranger/refdata-gex-GRCh38-2020-A/"
  mus_musculus: "/public/home/xiezhuoming/xzm/ref/10x/refdata-gex-mm10-2020-A/"

filter_empty:
  niters: 30000

qc:
  pct_counts_mt: 5
  total_counts: 60000
  n_genes_by_counts: 2000

dim_reduc:
  var_thresh: 0.75

cluster:
  res: 0.6